// The machine code generated by your program should go here

@LCL
D = M
@1
D = D+A
A = D
D = M
@SP
A = M
M = D
@SP
M = M+1

@LCL
D = M
@2
D = D+A
A = D
D = M
@SP
A = M
M = D
@SP
M = M+1

@SP  
AM = M-1 
D = M 
A = A-1 
M = D+M  

(END)
    @END
    0;JMP
