// The machine code generated by your program should go here

@LCL
D = M
@0
D = D+A
A = D
D = M
@SP
A = M
M = D
@SP
M = M+1

@ARG
D = M
@0
D = D+A
A = D
D = M
@SP
A = M
M = D
@SP
M = M+1


(END)
    @END
    0;JMP
