// The machine code generated by your program should go here

@1
D = A
@SP
A = M
M = D
@SP
M = M+1

@2
D = A
@SP
A = M
M = D
@SP
M = M+1

@SP 
M = M-1 
A = M 
D = M 
A = A-1 
D = M-D 
M = D

(END)
    @END
    0;JMP
